const ErrorCodes = {
  JOURNEY_NOT_FOUND: "JOURNEY_NOT_FOUND",
  JOURNEY_ALREADY_EXISTS: "JOURNEY_ALREADY_EXISTS",
  INVALID_JOURNEY: "INVALID_JOURNEY",
  USER_ALREADY_ONBOARDED: "USER_ALREADY_ONBOARDED",
  JOURNEY_INACTIVE: "JOURNEY_INACTIVE",
  INVALID_STAGE: "INVALID_STAGE",
  USER_NOT_ONBOARDED: "USER_NOT_ONBOARDED",
};

module.exports = { ErrorCodes };
